import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import { sanityClient, urlFor } from "../sanity.js";
import { Post } from "../typings";
import Link from "next/link";

interface Props {
  posts: [Post];
}
const Home = ({ posts }: Props) => {
  return (
    <div className="w-full">
      <Head>
        <title>Medium Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* ---------------------------- banner ---------------------------- */}
      <div className=" max-w-5xl mx-auto flex justify-between items-center bg-yellow-400 px-5 py-5 border-y md:border-y-0 border-black">
        <div className="">
          <h1 className="text-6xl max-w-xl font-serif">
            <span className=" underline  decoration-black decoration-4">
              Medium
            </span>{" "}
            is a place to write, read and connect
          </h1>
          <h2>
            It's easy and free to post your thinking on any topic and connect
            with millions of readers
          </h2>
        </div>
        <div>
          <h1 className=" font-serif hidden md:inline-flex h-32 lg:h-full text-4xl md:text-8xl lg:text-9xl font-bold">
            M
          </h1>
        </div>
      </div>

      {/* ------------------------- sanity posts links ------------------------- */}
      <div className="grid gap-5 grid-cols-1 md:grid-cols-2 lg:grid-cols-3 max-w-5xl mx-auto p-5">
        {posts.map((post) => {
          return (
            <Link key={post._id} href={`/post/${post.slug.current}`}>
              <div className=" rounded-md shadow-md overflow-hidden cursor-pointer ">
                <div className="w-full h-60 overflow-hidden object-cover object-center">
                  <Image
                    priority
                    src={urlFor(post.mainImage).url()!}
                    width={500}
                    height={350}
                    layout="responsive"
                    className="object-center object-cover"
                  />
                </div>
                <div>
                  <div className="flex justify-between px-5 pb-3 bg-white gap-5 items-start">
                    <div>
                      <p className="font-medium">{post.title}</p>
                      <p className="text-xs">
                        {post.description} by {post.author.name}
                      </p>
                    </div>
                    <div>
                      <Image
                        src={urlFor(post.author.image).url()!}
                        alt={post.author.name}
                        width={70}
                        height={70}
                        className="rounded-full"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </Link>
          );
        })}
      </div>
    </div>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const query = `*[_type=="post"]{
  _id,
  title,
  slug,
  author->{
  name, image
}, 
description, 
mainImage

}`;

  const posts = await sanityClient.fetch(query);

  return { props: { posts } };
};
